pre-release-replacements = [
  { file = "CHANGELOG.md", search = "Unreleased", replace = "{{version}}", prerelease = false },
  { file = "CHANGELOG.md", search = "ReleaseDate", replace = "{{date}}", prerelease = false },
]
