name: Cross-Platform CI

on:
  push:
    branches: [ chore/windows-cancel-test ]

jobs:
  test:
    name: Run sleep example
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]
        include:
          # - os: ubuntu-latest
          #   platform: Linux
          - os: windows-latest
            platform: Windows
          # - os: macos-latest
          #   platform: macOS

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    # - name: Run sleep example on ${{ matrix.platform }}
    #   run: cargo run --example sleep
    #   timeout-minutes: 10

    - name: start background server
      run: cargo run --example server > data.log &

    - name: wait for server to startup
      run: sleep 5

    - name: test sqlx
      run: cargo run --example sqlx
      timeout-minutes: 3

    - name: show logs
      if: ${{ always() }}
      run: cat data.log
